package main

import (
	"github.com/juanpipeline/star-wars-characters-api/api"
	"github.com/juanpipeline/star-wars-characters-api/db"

	"github.com/gin-gonic/gin"
	_ "github.com/juanpipeline/star-wars-characters-api/docs" // docs is generated by Swag CLI, you have to import it.
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Star wars characters API
// @version 1.0
// @description A simple APIRest to Star Wars character using Golang (gin,gorm).
// @termsOfService http://swagger.io/terms/

// @contact.name juanpipeline
// @contact.url https://github.com/juanpipeline

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

func setupRouter() *gin.Engine {
	// Migrate repository
	db.Migrate()
	r := gin.Default()
	starwars := r.Group("/star-wars")
	{
		characters := starwars.Group("/characters")
		{
			characters.GET(":id", api.GetCharacter)
			characters.DELETE(":id", api.DeleteCharacter)
			characters.PATCH(":id", api.UpdateCharacter)
			characters.GET("", api.SearchCharacters)
			characters.POST("", api.CreateCharacter)

		}
	}
	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	return r
}

func main() {
	r := setupRouter()
	// Listen and Server in 0.0.0.0:8080
	r.Run(":8080")
}
